version: '3.9'
services:
  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile
    image: php:8.2-apache
    container_name: "apache"
    volumes:
      - ./apache/html:/var/www/html/
      - ./apache/sites_enabled:/etc/apache2/sites_enabled
      - ./apache/php/custom-php.ini:/use/local/etc/php/conf.d/custom-php.ini
    ports:
      - "8080:80"
    networks:
      - sae-network

  postgres:
    container_name: "postgres"
    build:
      context: .
      dockerfile: postgres/Dockerfile
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5433:5433"
    networks:
      - sae-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    depends_on:
      - apache
    networks:
      - sae-network
    restart: unless-stopped

networks:
  sae-network:
    driver: bridge